language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  - "12"
before_install:
  - docker --version
  - docker-compose --version
install:
  - make start-test
script:
  - make run-test