version: '3.4'
services:
  postgres:
    image: postgres:11.3
    volumes: 
      - 'pg_data:/var/lib/postgresql/data'
  
  app:
    build:
      context: ./
    env_file: 
      - .env.example
    depends_on:
      - postgres
  
volumes:
  pg_data: